type Query {
    findPokemonById(id: Int!): Pokemon!
    findPokemonByName(name: String!): Pokemon!

    findTrainerById(id: ID!): Trainer!
    findTrainerByName(name: String!): Trainer!

    me: Trainer!

    findTeamById(id: ID!): Team!
    findAllTeams: [Team!]!
}

type Mutation {
    createTeam(name: String!): Team!

    addPokemonToTeamById(pokemonId: Int!):Team!
    addPokemonToTeamByName(pokemonName: String!):Team!

    removePokemonFromTeamById(id: ID!):Team!

    updateProfile(id:ID!, input: UpdateProfileInput!): Trainer!
    changePassword(input: ChangePasswordInput!): Boolean!

    deleteMyTrainer: Boolean!

    movePokemons(positions: [PokemonPositionInput!]!): Team!
}

type Trainer {
    id: ID!
    name: String!
    email: String!
    team: Team
}

type Team{
    id: ID!
    name: String!
    trainer: Trainer!
    pokemons: [TeamPokemon]
}

type Pokemon {
    id: Int!
    name: String!
    types: [String!]!
    moves: [String!]!
    position: Int!
}

type TeamPokemon {
    id: ID!
    pokemonId: Int!
    name: String!
    position: Int!
}

input UpdateProfileInput {
    name: String!
    email: String!
}

input ChangePasswordInput {
    currentPassword: String!
    newPassword: String!
}

input PokemonPositionInput {
    id: ID!
    position: Int!
}

