type Pokemon {
    id: Int!
    name: String!
    types: [String!]!
    moves: [String!]!
}

type Query {
    findPokemonById(id: Int!): Pokemon
    findPokemonByName(name: String!): Pokemon

    findTrainerById(id: ID!): Trainer
    findTrainerByName(name: String!): Trainer
    me: Trainer

    findTeamById(id: ID!): Team
    findAllTeams: [Team!]!
}

type Mutation {
    createTeam(trainerId: ID!, name: String!): Team

    addPokemonToTeam(pokemonId: ID!, teamId: ID!):Team
}


type Team{
    id: ID!
    name: String!
    pokemons: [Pokemon!]!
}

type Trainer {
    id: ID!
    name: String!
    email: String!
    password: String!
    team: Team
}
