spring:
  application:
    name: pokegateway
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${OAUTH0_CLIENT_ID}
            client-secret: ${OAUTH0_CLIENT_SECRET}
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: "https://dev-hndn80m8v8iqy45n.us.auth0.com/"

  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        format_SQL: true

server:
  address: 0.0.0.0
  port: 8080

auth0:
  audience: "http://poketeamsauth"

logging:
  level:
    root: DEBUG

pokemon.service:
  base-url: ${POKEMON_SERVICE_URL:http://localhost:8081}

jwt_secret: "devTest"

