spring:
  application:
    name: pokegateway
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG

pokemon.service:
  base-url: ${POKEMON_SERVICE_URL:http://localhost:8081}

jwt_secret: "devTest"

