spring:
  application:
    name: pokegateway
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO

pokemon.service:
  base-url: ${POKEMON_SERVICE_URL:http://localhost:8081}

jwt_secret: "devTest"

